#!/bin/bash

#check if it is a C++ build or a python build
if [ -f "CMakeLists.txt" ]
then
  # C++ build
  FOLDER="cmake-build-release"
  BUILDTYPE="Release"

  if [[ "$*1" == *"-d"*  ]]
  then
    FOLDER="cmake-build-debug"
    BUILDTYPE="Debug"
  fi

  TESTS="NO_TESTS"
  if [[ "$*1" == *"-t"*  ]]
  then
    TESTS=""
  fi

  if [ -d "$FOLDER" ]
  then
    if [[ "$*1" == *"-c"*  ]]
    then
      rm $FOLDER -r
    fi
  fi
  if [ -d "dependencies" ]
  then
    if [[ "$*1" == *"-cd"*  ]]
    then
      rm dependencies -r -f
    fi
  fi
  mkdir $FOLDER -p

  cd $FOLDER
  export CATCH_TESTS="$TESTS"
  cmake .. -DCMAKE_BUILD_TYPE=$BUILDTYPE '-DCMAKE_CXX_COMPILER=/bin/g++-10'

  if [[ "$*1" == *"-i"*  ]]
  then
    make install
  else
    make -j
  fi
else
  # python build
  echo "No cmake project file found (CMakeLists.txt)"
fi
