#!/bin/bash

temp=$(mktemp -d)

echo "Installing scripts"

curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/build?-H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/build
chmod +777 $temp/build
sudo cp $temp/build /usr/local/bin/build

curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/python-module-build.py -H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/python-module-build.py
chmod +777 $temp/python-module-build.py
sudo cp $temp/python-module-build.py /usr/local/bin/python-module-build.py

curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/python-module-install.py -H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/python-module-install.py
chmod +777 $temp/python-module-install.py
sudo cp $temp/python-module-install.py /usr/local/bin/python-module-install.py

echo "Installing cmake module"
curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/DependenciesConfig.cmake -H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/DependenciesConfig.cmake
curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/CMakeLists.txt -H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/CMakeLists.txt

cd $temp
cmake . ~> /dev/null
sudo make install ~> /dev/null

echo "Installing python module"
mkdir dependencies
curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/dependencies/__init__.py -H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/dependencies/__init__.py
curl -s https://raw.githubusercontent.com/germanespinosa/dependencies/main/dependencies/__version__.py -H "Cache-Control: no-cache, no-store, must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"> $temp/dependencies/__version__.py
cd dependencies
python __init__.py
